# Generated by Django 3.1.4 on 2021-04-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='jumlah',
            field=models.IntegerField(null=True),
        ),
    ]
