# Generated by Django 3.1.4 on 2021-04-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0003_auto_20210418_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='judul',
            field=models.CharField(max_length=50),
        ),
    ]
