# Generated by Django 3.1.4 on 2021-04-18 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0004_auto_20210418_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='kelompok',
            new_name='kelompok_id',
        ),
    ]
