# Generated by Django 3.1.4 on 2021-04-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0005_auto_20210418_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='buku',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
